# SCCS PowerShell Profile Templates
# Static blocks emitted by the Fish->PowerShell converter.

PROFILE_HEADER = """# Microsoft.PowerShell_profile.ps1
# Auto-generated by `sccs convert fish-to-pwsh`.
# Hand edits in this file are preserved by `sccs sync`, but will be overwritten
# on the next `sccs convert fish-to-pwsh --force`.
# Prefer editing the modular files under conf.d/ and functions/.
"""

PROFILE_LOADER = """
# Load all conf.d/*.ps1 in lexicographic order.
$confDir = Join-Path $PSScriptRoot 'conf.d'
if (Test-Path $confDir) {
    Get-ChildItem -Path $confDir -Filter '*.ps1' | Sort-Object Name |
        ForEach-Object { . $_.FullName }
}

# Load all functions/*.ps1 (no ordering guarantee).
$fnDir = Join-Path $PSScriptRoot 'functions'
if (Test-Path $fnDir) {
    Get-ChildItem -Path $fnDir -Filter '*.ps1' |
        ForEach-Object { . $_.FullName }
}
"""

CONFD_FILE_HEADER = """# {filename}
# Auto-generated from {source_rel} by `sccs convert fish-to-pwsh`.
# Lines marked `# fish-original:` had no automatic PowerShell equivalent;
# port them by hand if you need them on Windows.
"""

FUNCTION_STUB_HEADER = """# {filename}
# Auto-generated stub from {source_rel} by `sccs convert fish-to-pwsh`.
# Fish function bodies are not auto-portable. The original Fish source
# is preserved below as a comment block — port to PowerShell by hand.
"""


README_TEMPLATE = """# PowerShell Profile (Generated)

This directory is **auto-generated** by `sccs convert fish-to-pwsh` from the
Fish shell configuration under `~/.config/fish/` on macOS or Linux.

## Layout

```
.config/powershell/
├── Microsoft.PowerShell_profile.ps1   # Entry point — dot-sources conf.d + functions
├── conf.d/
│   ├── 00-env.ps1            # Environment variables (set -gx → $env:VAR)
│   ├── 29-coreutils.ps1      # Coreutils replacements (Set-Alias)
│   ├── 30-aliases-system.ps1
│   ├── 31-aliases-git.ps1
│   ├── 32-aliases-docker.ps1
│   └── ...
└── functions/
    └── *.ps1                 # Fish function stubs — port by hand
```

## Sync to Windows

On Windows 11 with PowerShell 7+:

```powershell
sccs config init
sccs categories enable powershell_profile
sccs sync --category powershell_profile
```

The profile is installed under `~/Documents/PowerShell/`. With OneDrive sync
enabled, this may resolve to `~/OneDrive/Documents/PowerShell/` — override
`local_path` for the `powershell_profile` category in your config if needed.

## Editing

- **Add an alias on Windows**: edit `conf.d/30-aliases-system.ps1` directly
  on the Windows machine; the next `sccs sync` pushes it back to the repo.
- **Add an alias on macOS/Linux**: edit the matching Fish file under
  `~/.config/fish/conf.d/` and re-run `sccs convert fish-to-pwsh --force`.
- **Port a Fish function**: open the corresponding stub in `functions/`,
  translate the body to PowerShell, remove the `# fish-original:` comment.

## Limitations

- Fish-specific syntax (`begin/end`, `string match`, `switch`, `$argv[N]`) has
  no automatic mapping. All Fish functions are emitted as stub comments.
- Aliases pointing to GNU/macOS-only binaries (e.g. `uu-cat` from
  `uutils-coreutils`) require the binary to be installed on Windows; use
  `scoop install uutils-coreutils` to enable them.
- `*.macos.fish` and `*.linux.fish` files are skipped during conversion.
"""
