# SCCS Zsh Profile Templates
# Static blocks emitted by the Fish->Zsh converter.

ZSHRC_HEADER = """# zshrc — entry point for the generated zsh profile
# Auto-generated by `sccs convert fish-to-zsh`.
# Hand edits in this file are preserved by `sccs sync`, but will be overwritten
# on the next `sccs convert fish-to-zsh --force`.
# Prefer editing the modular files under conf.d/ and functions/.
#
# Activate by adding this line to your ~/.zshrc (SCCS never edits it for you):
#   source ~/.config/zsh/zshrc
"""

ZSHRC_LOADER = """
# Resolve the directory this file lives in (works when sourced).
_sccs_zsh_dir="${${(%):-%N}:A:h}"

# Load all conf.d/*.zsh in lexicographic order.
if [[ -d "$_sccs_zsh_dir/conf.d" ]]; then
  for _sccs_zsh_file in "$_sccs_zsh_dir"/conf.d/*.zsh(N); do
    source "$_sccs_zsh_file"
  done
fi

# Load all functions/*.zsh (no ordering guarantee).
if [[ -d "$_sccs_zsh_dir/functions" ]]; then
  for _sccs_zsh_file in "$_sccs_zsh_dir"/functions/*.zsh(N); do
    source "$_sccs_zsh_file"
  done
fi
unset _sccs_zsh_dir _sccs_zsh_file
"""

CONFD_FILE_HEADER = """# {filename}
# Auto-generated from {source_rel} by `sccs convert fish-to-zsh`.
# Lines marked `# fish-untranslated:` had no confident zsh equivalent;
# port them by hand if you need them.
"""

FUNCTION_FILE_HEADER = """# {filename}
# Auto-generated from {source_rel} by `sccs convert fish-to-zsh`.
# Best-effort translation of the fish function — review before relying on it.
# Lines marked `# fish-untranslated:` had no confident zsh equivalent.
"""

FUNCTION_STUB_HEADER = """# {filename}
# Auto-generated stub from {source_rel} by `sccs convert fish-to-zsh`.
# This fish function could not be confidently auto-translated ({reason}).
# The original fish source is preserved below as a comment block — port to
# zsh by hand.
"""

# Uname guard wrapping for platform-specific fish files (*.macos.fish /
# *.linux.fish). Unlike the PowerShell converter, these files ARE converted
# for zsh — guarded so one generated profile works on both platforms.
UNAME_GUARD_HEADER = """if [[ "$(uname)" == "{uname_value}" ]]; then"""
UNAME_GUARD_FOOTER = "fi"


# Curated comfort shortcuts emitted as conf.d/95-conveniences.zsh.
# Deliberately minimal compared to the PowerShell variant: converted fish
# aliases (ll, la, ...) work natively in zsh, so only genuinely missing
# niceties are added here.
CONVENIENCES_BLOCK = """# 95-conveniences.zsh
# Auto-generated by `sccs convert fish-to-zsh`.
#
# Small comfort shortcuts zsh does not ship by default. Loads last in
# conf.d/. Edit or delete this file to customize; re-run with
# `--no-conveniences` to skip it.

# --- Navigation (type `..` instead of `cd ..`) ---
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# mkcd: create a directory (incl. parents) and change into it.
mkcd() {
  mkdir -p -- "$1" && cd -- "$1"
}
"""


README_TEMPLATE = """# Zsh Profile (Generated)

This directory is **auto-generated** by `sccs convert fish-to-zsh` from the
Fish shell configuration under `~/.config/fish/`. It makes the fish aliases,
environment variables and functions available natively in zsh — useful on
machines where fish is not installed (e.g. a stock macOS zsh).

## Activation

Add this single line to your `~/.zshrc` (SCCS never edits `~/.zshrc` itself):

```zsh
source ~/.config/zsh/zshrc
```

## Layout

```
.config/zsh/
├── zshrc                     # Entry point — sources conf.d + functions
├── conf.d/
│   ├── 00-env.zsh            # Environment variables (set -gx → export)
│   ├── 30-aliases-system.zsh
│   ├── 30-aliases.macos.zsh  # Wrapped in a `uname == Darwin` guard
│   ├── ...
│   └── 95-conveniences.zsh   # Extras zsh lacks (.., ..., mkcd)
└── functions/
    └── *.zsh                 # Best-effort translated fish functions
```

## Sync to another machine

```bash
sccs categories enable zsh_config
sccs sync --category zsh_config
```

The profile lands in `~/.config/zsh/` on the target machine; add the
activation line to `~/.zshrc` there once.

## Editing

- **Add an alias**: edit the matching fish file under `~/.config/fish/conf.d/`
  and re-run `sccs convert fish-to-zsh --force` — fish stays the source of
  truth.
- **Fix a translated function**: functions are translated best-effort; review
  anything marked `# fish-untranslated:` and port those lines by hand. Files
  that were too fish-specific are emitted as fully commented stubs.

## Limitations

- Fish builtins without zsh equivalents (`string`, `math`, `argparse`,
  universal variables `set -U`, `psub`) are preserved as
  `# fish-untranslated:` comments.
- Functions using fish event handlers (`--on-event`, `--on-variable`, ...)
  are emitted as stubs.
- `*.macos.fish` / `*.linux.fish` files are converted inside a
  `[[ "$(uname)" == ... ]]` guard, so the generated profile is safe to load
  on both platforms.
"""
