# SCCS Doctor — Managed Files Registry
#
# `sccs doctor install` installs system components (npx tools, Claude
# plugins) that drop files into ~/.claude/{skills,hooks,agents,...}/.
# Those files are reproducible from the doctor manifest, so they should
# NOT participate in `sccs sync` — otherwise two machines that ran
# `sccs doctor install` independently produce subtly different file
# contents and conflict on every pull.
#
# This module returns the glob patterns that the sync engine merges into
# its `global_exclude` list so doctor-managed files are silently skipped.

from __future__ import annotations

from sccs.doctor.schema import DoctorConfig

# Hardcoded mapping: bundled doctor tool name → glob patterns it manages
# inside ~/.claude/. Patterns are matched against the basename of each
# scanned skill/agent/hook (see sccs/utils/paths.py:matches_any_pattern),
# so `gsd-*` matches the directory `~/.claude/skills/gsd-manager/` and
# files like `~/.claude/hooks/gsd-phase-boundary.sh` alike.
DEFAULT_MANAGED_PATTERNS: dict[str, list[str]] = {
    # `npx get-shit-done-cc --claude --global --force-statusline` writes
    # gsd-* skills, agents and hooks directly under ~/.claude/. These are
    # regenerated by every install, so syncing them across machines just
    # produces conflicts.
    "get-shit-done-cc": ["gsd-*"],
    # `sccs doctor` copies `@playwright/cli/skills/playwright-cli/` from
    # the npm global root into `~/.claude/skills/playwright-cli/` after
    # every install/update. The npm package is the source of truth, so
    # syncing the directory across machines would just shadow the latest
    # bundled version with a stale snapshot from another host.
    "playwright-cli": ["playwright-cli"],
}


def get_doctor_managed_excludes(doctor_config: DoctorConfig) -> list[str]:
    """Return the glob patterns the sync engine should exclude.

    Combines:
      * Hardcoded `DEFAULT_MANAGED_PATTERNS` for any bundled npx tool
        configured in the user's `doctor.npx_tools` (or its defaults).
      * User-supplied `doctor.managed_excludes` for additional plugins or
        custom tooling.

    Returns a deduplicated, sorted list so the merge is deterministic
    across calls.
    """
    patterns: set[str] = set()

    for tool in doctor_config.effective_npx_tools():
        patterns.update(DEFAULT_MANAGED_PATTERNS.get(tool.name, []))

    patterns.update(doctor_config.managed_excludes)

    return sorted(patterns)
